package com.youmeek.ssm.module.user.entities;


public class SysUser1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user1.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user1.user_login_name
     *
     * @mbggenerated
     */
    private String userLoginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user1.user_login_password
     *
     * @mbggenerated
     */
    private String userLoginPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user1.user_email
     *
     * @mbggenerated
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user1.user_age
     *
     * @mbggenerated
     */
    private String userAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user1.user_id
     *
     * @return the value of sys_user1.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user1.user_id
     *
     * @param userId the value for sys_user1.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user1.user_login_name
     *
     * @return the value of sys_user1.user_login_name
     *
     * @mbggenerated
     */
    public String getUserLoginName() {
        return userLoginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user1.user_login_name
     *
     * @param userLoginName the value for sys_user1.user_login_name
     *
     * @mbggenerated
     */
    public void setUserLoginName(String userLoginName) {
        this.userLoginName = userLoginName == null ? null : userLoginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user1.user_login_password
     *
     * @return the value of sys_user1.user_login_password
     *
     * @mbggenerated
     */
    public String getUserLoginPassword() {
        return userLoginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user1.user_login_password
     *
     * @param userLoginPassword the value for sys_user1.user_login_password
     *
     * @mbggenerated
     */
    public void setUserLoginPassword(String userLoginPassword) {
        this.userLoginPassword = userLoginPassword == null ? null : userLoginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user1.user_email
     *
     * @return the value of sys_user1.user_email
     *
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user1.user_email
     *
     * @param userEmail the value for sys_user1.user_email
     *
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user1.user_age
     *
     * @return the value of sys_user1.user_age
     *
     * @mbggenerated
     */
    public String getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user1.user_age
     *
     * @param userAge the value for sys_user1.user_age
     *
     * @mbggenerated
     */
    public void setUserAge(String userAge) {
        this.userAge = userAge == null ? null : userAge.trim();
    }
}